### ISSUE TITLE
1.0.6.2 Test Build Issues

### ISSUE THREAD

**Issue by ebayShopper** [EpochModTeam/DayZ-Epoch#2000]
The **[[1.0.6.2 test build]](https://github.com/EpochModTeam/DayZ-Epoch/tree/master/Test%20Build)** is now available. Please report any bugs or issues here.

For the list of changes that need testing see the **[change log](https://github.com/EpochModTeam/DayZ-Epoch/blob/master/CHANGE%20LOG%201.0.6.2.txt)** with special attention to:
- New L85s and SVDs
- Headlight behavior on all vehicles
- Clean up of destroyed vehicles after 5 minutes
- Duping methods described in #1936 #1938 #1959 should no longer be reproducible
- Group saving after death, relog and clothes change
- Dropping radio and picking it back up when in a group and `dayz_requireRadio = true;`
- Trading, especially selling vehicles, upgraded and normal, with and without the key
- Server-side sender verification, the following actions are affected:
	- Building
	- Upgrading buildables, vehicles and tents
	- Downgrading buildables
	- Buying and selling vehicles
	- Destroying tents
	- Destroying drivable vehicles
	- Removing buildables, safes, tents, traps and wrecks
	- Triggering traps
- The zero buildings below have new or updated interiors:
```
"Land_houseV_2T2","Land_Mil_ControlTower","Land_Mil_House",
"Land_A_MunicipalOffice","Land_HouseV_1I3","Land_Shed_W4","Land_A_TVTower_Base",
"Land_a_stationhouse","Land_Mil_Barracks","Land_Misc_PowerStation"
```

Known issues:
- Ladder directions are wrong in Land_Mil_House
- Back entrance stairs are too high on most of the Land_houseV_2T2 (will be fixed with model update)
- Fn_exitSwim does not work on player zombies

Please do not post issues with third party scripts here. Include relevant errors from client or server RPT:

```
Client RPT: C:\Users\YourName\AppData\Local\ArmA 2 OA\arma2oa.RPT (enable show hidden files in Windows to see it)
Server RPT: FTP\server config directory\arma2oaserver.RPT

Make sure client is not started with -noLogs param (Settings > uncheck -noLogs and check -showScriptErrors in DayZLauncher).
```

I made a basic user interface for quickly testing most things without worrying about compatibility conflicts: 
**[[You can get it here]](https://github.com/ebayShopper/TestKit).**

Note BE scripts.txt may need to be disabled during testing because it is not fully up to date yet.

**Comment by SmokeyBR** [comment]
- headlight behaviour MTVR´s have narrow lights, some vehicles have glare when looking at it some dont. https://imgur.com/a/ry6AV (did not test all)
- Clean up of destroyed vehicles after 5 minutes, tested and working.
- Kamaz_DZE takes ALOT to dmg 1 wheel
- M240Nest_DZ player camera will fix on the object (M240Nest_DZ) when getting out if this happens. https://imgur.com/a/Zi7Cp

**Comment by ebayShopper** [comment]
M240 nest issue is fixed with b9c9d50.

**Comment by SmokeyBR** [comment]
while testing ive been thinking of some suggestions to be put on the default dayzepoch mod if possible before 1;0;6.2 is released.
1. Show Door Code on Door management interface if player is owner.
2. Be able to destroy base objects with satchel charges ONLY.
3. Add safe/lockbox manager, based on door management.

**Comment by worldwidesorrow** [comment]
When testing the new L85 variants in WAI, I noticed that it is assigning non-SD magazines to the SD variants. The screenshot shows me looting an ai body.

https://github.com/worldwidesorrow/RandomDayZ/blob/master/L85%20SD%20Problem.jpg

**Comment by ndavalos** [comment]
So I'm having a little trouble figuring out how to get the zombies to behave like they used to. I don't want to have slow zombies, but whatever I try to put in the new array for controlling them makes them slow no matter what. Am I missing something? Maybe I'm not understanding the config for it now.

**Comment by worldwidesorrow** [comment]
I noticed that right click actions are disabled for ItemRadio when the group system is disabled. Is there a way that this can be modified because WAI has an option to use the radio to toggle notifications on and off.  I removed the check in ui_selectSlot.sqf, which works, but the inoperable option for opening the group system still shows up.

**Comment by ebayShopper** [comment]
@worldwidesorrow You can disable that by commenting [[this line]](https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/ui_selectSlot.sqf#L23).

You can then skip adding the default right click actions for any item. Just add an exit in the first for loop. For example add this:
```sqf
if (_item == "ItemRadio") exitWith {};
```
Right below [[this line]](https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/ui_selectSlot.sqf#L47)

You need to modify that file anyway to add custom right click actions.

**Comment by worldwidesorrow** [comment]
That didn't work out. I get this when I right click the radio https://github.com/worldwidesorrow/RandomDayZ/blob/master/rightclick.jpg

This is the whole file with your suggestions. The extra rc loop is in there as well. https://github.com/worldwidesorrow/RandomDayZ/blob/master/ui_selectSlot.sqf

**Comment by ebayShopper** [comment]
@worldwidesorrow this should work:
```
if (_item == "ItemRadio") exitWith {_numActions = 0;};
```
If it doesn't just message me on the forums or Discord so we don't spam peoples' Github notifications.

**Comment by AirwavesMan** [comment]
I noticed a strange behavior while spawning. Happend with a new spawned and old character. I got this problem not on Chernaus because I tested it not for a long time there. Tested map was Panthera. 

When logging in I have sometimes broken legs, sometimes the player screams of pain but is not damaged, sometimes the player cough but he has no infection. That happend only after a relog or a new login. I had that a log time ago after I updated a commit from 1.0.6.2 (commit was before June) to my live server but I dont remember which one. It had something to do with the player_monitor.fsm or the player_switchModel.sqf.

I cannot reproduce it but it happend a way to often.

**Comment by ebayShopper** [comment]
I tested relogging and respawning a couple times on Napf and Panthera, but I could not reproduce that @AirwavesMan. 

There are many things that could cause that on a modified server. Your character will never cough in the default files [unless r_player_infected returns true](https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/system/scheduler/sched_medical.sqf#L137), so you got infected somehow. Your character was most likely held in the water too long during spawn in and got sick from low temperature. The `respawn_west` marker position is in the water on Panthera and some other island maps. 

If a script spawns objects on the `respawn_west` marker position players can get crushed when they log in or change clothes. The "panic" or "scream" sound only plays in the default files when [your player is attacked by zombies](https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/player_zombieCheck.sqf#L134-L141). If you hear that on login my guess is a building or object got spawned on the `respawn_west` marker position by some script on your server and it is spawning zombies there. I would teleport there and check the next time it happens to you. `player setPosATL respawn_west_original;`

If you find steps to reproduce it consistently with the stock files then let me know.
