### ISSUE TITLE
Launchers that have same name as ammo don't show in sell list

### ISSUE THREAD

**Issue by ndavalos** [EpochModTeam/DayZ-Epoch#2007]
This line:
https://github.com/EpochModTeam/DayZ-Epoch/blob/efaf1f93990eba7b8b71be1c7b6c12cd9e95884b/SQF/dayz_code/actions/AdvancedTrading/functions/z_at_checkArrayInConfig.sqf#L63

Causes things like Igla, Stinger etc to attempt to add the item to the sell list on the first occurrence of the item in the trader categories. So if it finds it in trade_items, but it's actually a weapon, it will attempt to add it, but when it gets to this line: 
https://github.com/EpochModTeam/DayZ-Epoch/blob/efaf1f93990eba7b8b71be1c7b6c12cd9e95884b/SQF/dayz_code/actions/AdvancedTrading/functions/z_at_checkArrayInConfig.sqf#L98

It fails to add it when the category first checked is not the same as the passed category. 

For instance, if you have an Igla in on the trader under a category as a weapon, and the ammo (Igla) in a second category on the same trader, it will sometimes find the ammo first when iterating through the categories. 
This line tells it to continue because it exists in the currently checked category: (passed in as weapon, but this line finds the ammo first)
https://github.com/EpochModTeam/DayZ-Epoch/blob/efaf1f93990eba7b8b71be1c7b6c12cd9e95884b/SQF/dayz_code/actions/AdvancedTrading/functions/z_at_checkArrayInConfig.sqf#L63

When it gets to:
https://github.com/EpochModTeam/DayZ-Epoch/blob/efaf1f93990eba7b8b71be1c7b6c12cd9e95884b/SQF/dayz_code/actions/AdvancedTrading/functions/z_at_checkArrayInConfig.sqf#L98

The passed category doesn't match the found category type (trade_weapon vs found type of trade_item), so it skips adding it to the list.

**Comment by ndavalos** [comment]
It appears to fix itself if you simply do:
```
			_continue = (isClass(missionConfigFile >> "CfgTraderCategory" >> _cat >> _y)) && ((getText(missionConfigFile >> "CfgTraderCategory" >> _cat >> _y >> "type")) == _passedType);
			if (_continue) exitWith {
```
I fixed it locally, but I customize stuff myself so much that I don't really want to push an update out and sort it all out. Give this a try and see if it fixes the problem. I tested with an Igla and ammo and both sold for the appropriate amounts.

**Comment by ebayShopper** [comment]
Thanks, I forgot to account for some traders (like hero, bandit, blackmarket) having both weapon and ammo categories in e1b6125. Fixed in  2a2198a.

The code you posted will error on the second condition when the class doesn't exist, because you forgot to use { } lazy evaluation. Also `_passedType` is "find" for vehicles, so it will not work in that case.
